# Generated by Django 4.0.4 on 2022-06-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='faculté',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.faculte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.section'),
            preserve_default=False,
        ),
    ]
