# Generated by Django 4.0.4 on 2022-05-16 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='id',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom_utilisateur',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_utilisateur',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 6, 29, 55221, tzinfo=utc)),
        ),
    ]
