# Generated by Django 4.0.4 on 2022-05-16 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_enseignant_nom_utilisateur_etudiant_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 15, 31, 20, 418320, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 15, 31, 20, 418320, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_utilisateur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 15, 31, 20, 418320, tzinfo=utc), editable=False),
        ),
    ]
