# Generated by Django 4.0.4 on 2022-05-16 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_enseignant_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='etudiant_note',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 15, 37, 52, 629472, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 15, 37, 52, 629472, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 15, 37, 52, 612329, tzinfo=utc), editable=False),
        ),
    ]
