# Generated by Django 4.0.4 on 2022-05-16 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_commentaire_date_alter_commentaire_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 15, 38, 31, 717837, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 15, 38, 31, 717837, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 15, 38, 31, 717837, tzinfo=utc), editable=False),
        ),
    ]
