# Generated by Django 4.0.4 on 2022-05-16 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_note_etudiant_alter_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_utilisateur',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 32, 18, 341424, tzinfo=utc)),
        ),
    ]
