# Generated by Django 4.0.4 on 2022-05-16 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_etudiant_id_note_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 36, 30, 777504, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 36, 30, 777504, tzinfo=utc)),
        ),
    ]
