# Generated by Django 4.0.4 on 2022-05-16 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_commentaire_date_alter_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 40, 27, 80510, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 40, 27, 64888, tzinfo=utc)),
        ),
    ]
