# Generated by Django 4.0.4 on 2022-05-16 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_commentaire_date_alter_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='etudiant',
            new_name='etudiant_note',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 12, 57, 48, 73780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 57, 48, 73780, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom_utilisateur',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(choices=[('INFO', 'Informatique'), ('PHY', 'physique'), ('CH', 'chimie '), ('BIO', 'Biologie'), ('GEO', 'Geologie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_utilisateur',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='specialite',
            field=models.CharField(choices=[('INFO', 'Informatique'), ('PHY', 'physique'), ('CH', 'chimie '), ('BIO', 'Biologie'), ('GEO', 'Geologie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 12, 57, 48, 73780, tzinfo=utc), editable=False),
        ),
    ]
