# Generated by Django 4.0.4 on 2022-05-16 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_rename_etudiant_note_etudiant_note_commentaire_heure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='etudiant_note',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 13, 2, 55, 692605, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 13, 2, 55, 692605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 13, 2, 55, 692605, tzinfo=utc), editable=False),
        ),
    ]
