# Generated by Django 4.0.4 on 2022-05-16 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_note_etudiant_note_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='nom_utilisateur',
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant_note',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 13, 5, 56, 587519, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 13, 5, 56, 587519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 13, 5, 56, 586486, tzinfo=utc), editable=False),
        ),
    ]
